### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by Jose76Tron** [sigsegv-mvm/sigsegv-mvm#1]
Hello, i tried to compile this on Visual Studio 2017 community version and it compiled nice then i uploaded the .dll file to the sourcemod extensions folder but it shows this error

[04] <FAILED> file "sigsegv.ext.tf2.dll": error code 0000007e

and if i load it, it crashes with this error
https://cdn.discordapp.com/attachments/299575073264762881/400712210688507904/unknown.png

any fix?

**Comment by Jose76Tron** [comment]
Crash dump https://crash.limetech.org/24aulgvh6yky

**Comment by Jose76Tron** [comment]
bump, any help?

**Comment by sigsegv-mvm** [comment]
Apologies for the delay; I know you've attempted to contact me through a few different channels. I'm looking into this now.

**Comment by Jose76Tron** [comment]
Oh, ok sorry for the spam, thanks for looking it :D

**Comment by Jose76Tron** [comment]
Btw i compiled the last commit and i still get this error http://prntscr.com/i0xzws

**Comment by sigsegv-mvm** [comment]
Right, the commits I pushed earlier were just some general cleanups for the MSVC project file, nothing specific to your error.

I'll be pushing a branch later that adds some extra logging, so we can get some extra info out of your situation.

In the meantime, the crash dump you linked me to doesn't seem to have debug info for the `sigsegv.ext.2.tf2.dll` library, so I can't tell which functions are in the stack trace... I don't know how the Accelerator/Throttle system works, but is there a way to upload a PDB file (or some other debug information file) to that web UI along with the dump? Or could you at least make sure you're copying both the `sigsegv.ext.2.tf2.dll` and `sigsegv.ext.2.tf2.pdb` files to the SourceMod extensions folder after each build?

Oh, and can you get the lines from the console log from right before when the crash happens? That might have some useful info now; and if not, it will later when I've added extra logging.

**Comment by sigsegv-mvm** [comment]
Also: if it's feasible for you to find and upload the actual dump file itself (`.dmp`), that'd likely be far more useful to me than faffing about with Accelerator/Throttle.

If you *aren't* able to find the dump file, but *are* able to get Visual Studio to debug the program (e.g. by hitting **Retry** on the Assertion Failure dialog box), then once VS is open, you can do **Debug > Save Dump As...** and save out a `.dmp` file. (In the **Save** dialog, make sure **Minidump (.dmp)** is selected, not **Minidump with Heap (.dmp)**, or else it'll be a giant file.)

**Comment by Jose76Tron** [comment]
Yeah im copying the .dll and the .pdb after each build but same error, on the console theres nothing, at the same time i type "sm exts load sigsegv" or try to load it with autoload it crash with the same error it dosnt say anything at the console, idk if this works but accelerator created a dump file and a log file, 
[fbc1ad8e-d75c-4607-96be-d67f89929018.zip](https://github.com/sigsegv-mvm/sigsegv-mvm/files/1633223/fbc1ad8e-d75c-4607-96be-d67f89929018.zip)

**Comment by Jose76Tron** [comment]
btw sorry about my english, im from spain and my english isnt very good xD

**Comment by sigsegv-mvm** [comment]
> btw sorry about my english, im from spain and my english isnt very good xD

No worries!

I think that `.dmp` file will work; could you do me a favor upload the DLL and PDB files from the same exact build too?

**Comment by Jose76Tron** [comment]
There you have [Binary.zip](https://github.com/sigsegv-mvm/sigsegv-mvm/files/1633232/Binary.zip)

**Comment by sigsegv-mvm** [comment]
Okay thanks. Having the crash dump with the binaries helps me tremendously with debugging this.

I've already figured out what the problem is. My extension is **supposed to be** super-flexible about which of the Source Engine libraries it finds, and it only attempts to load the ones that are actually present. (So for example, there are some DLL's that are only there if it's a listen server, which won't be there if it's a dedicated server; e.g. `client.dll`.)

But it just so happens that I basically never run my own extension on a Windows dedicated server; when I do use the Windows build, it's virtually always on a listen server. And so those additional DLL's like `client.dll` are there.

And it turns out that there are some cases where I was sloppy with the code, and mistakenly didn't do the proper checks, meaning that even on a dedicated server it'll still attempt to access stuff in DLL's like `client.dll`. Which doesn't exist on a dedicated server. And of course since I don't test on Windows srcds much if ever, the problem never came up for me.

I should have this issue fixed up within an hour; maybe less. Thanks for the report!

**Comment by Jose76Tron** [comment]
Ok thanks! :D im really hyped to try the extension
